name: phpstan

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: core/
          php_version: 8.0